### ISSUE TITLE
About DLA-34

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/CenterNet-plus#1]
@yjh0410 
Hi!

You did a great job.

I did the benchmark test to find optimal backbone in terms of the execution time and imagenet top1 accuracy.

https://github.com/developer0hye/pytorch-backbone-benchmark

You can see DLA-34 is not heavy in comparison to other networks.

But you mentioned

CenterNet is an encoder-decoder network, but I won't consider Hourglass-101 or **DLA-34** in this project as they are both **too heavy and time consuming**.

DLA-34 should be a good choice as the backbone network real time object detector.

I think that the neck of DLA-34 proposed in CenterNet paper is little heavy, but I guess we can get a good results if we use your simple neck structure

It's just opinion. I love your work.

**Comment by yjh0410** [comment]
Wow！Wonderful！


Your jobs is very significant.


I must admit that I do have a misunderstanding of DLA-34. I will try this efficient network in the future.


Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上10:47
***@***.***&gt;;
抄送:&nbsp;"ら ***@***.******@***.***&gt;;
主题:&nbsp;[yjh0410/CenterNet-plus] About DLA-34 (#1)





 
@yjh0410
 Hi!
 
You did great job.
 
I did the benchmark test to find optimal backbone in terms of the execution time and imagenet top1 accuracy.
 
https://github.com/developer0hye/pytorch-backbone-benchmark
 
You can see DLA-34 is not heavy in comparison to other networks.
 
But you mentioned
 
CenterNet is an encoder-decoder network, but I won't consider Hourglass-101 or DLA-34 in this project as they are both too heavy and time consuming.
 
DLA-34 should be a good choice as the backbone network real time object detector.
 
It's just opinion. I love your work.
