### ISSUE TITLE
Number of classes

### ISSUE THREAD

**Issue by YashRunwal** [yjh0410/CenterNet-plus#17]
Hello @yjh0410 ,

I am training the model for the following classes: 
`class_labels = [ 'person', 'bicycle', 'motorcycle', 'car', 'train', 'truck', 'bus']`

Do I need to include the background class and pass the `self.num_classes == 8` or the background class should be ignored and the `self.num_classes should be 7`?

I think this may be the reason why I got 0 mAP before.

**Comment by yjh0410** [comment]
You should set it as 7, not 8.
