### ISSUE TITLE
DLA34 with Dilated Conv

### ISSUE THREAD

**Issue by minhhoangbui** [yjh0410/CenterNet-plus#19]
I have implemented myself this version. However, its accuracy doesn't exceed my expectation. Do you have any comments?
I really appreciate that.

https://gist.github.com/minhhoangbui/43f658f69d8c6a22952b74c408ac34e8

**Comment by yjh0410** [comment]
I also tried to use DLA34 as the backbone but got a poor result, 35 mAP lower than the 37.4 mAP of CenterNet-DLA34.
I have no good solution for this problem.
